### ISSUE TITLE
Adding a report function to the Admin interface

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#125]
It would be useful to create reports in the Admin interface.  Basically I consider a report to be like a ModelAdmin interface without the model or change page, or maybe it's like an alternate admin interface. In any case it is not a new idea and there are packages out there to add this functionality to Django.  Here are 3:
https://github.com/jsocol/django-adminplus
https://media.readthedocs.org/pdf/django-report-builder/latest/django-report-builder.pdf
https://pypi.python.org/pypi/django-reporting

We should look for others, then review them all and choose one for implementation.
The review should compare at least:
1. ease of implementation
2. how widely is it used? 
3. Is the code up to date?
4. Is there documentation? Tutorials or examples?

Please add other crtieria for review and other options to consider.

**Comment by Luke-Malchow-Bergenthal** [comment]
Closing due to ambiguity. What would an admin report entail?

What's more, it is probably better to just create front-end pages with restricted access in lieu of using the admin.
