### ISSUE TITLE
Add compound on Front End needs a link to ChemBL

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#267]
Since the user must enter the CHEMBLID, it would be convenient to have a link to CHEMBL (opens in a new tab) to look up the ID.  What would be slick is if you could find the compound in CHEMBL and simply go back to the MPS tab and retrieve the info (i.e. the software would find the CHEMBLID in the web page on the other tab).  It would be sufficient though if the user found the CHEMBLID and then copy-paste to the MPS tab.
There should be hints of text formats on the Add Compound fields.  Perhaps Acetaminophen could be the example for the hints.

**Comment by Luke-Malchow-Bergenthal** [comment]
What hints do you think would be necessary/helpful?

**Comment by Luke-Malchow-Bergenthal** [comment]
As of https://github.com/UPDDI/mps-database-server/commit/c0b0766434844118496df1f06e6ec77f278889ce the Compound Add page now has a link to ChEMBL that will try to open in a new tab (depending on the user's browser settings, it may appear in a new window).
