### ISSUE TITLE
Change instruction in Add Compound GUI

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#271]
In the Add Compound GUI we should  change the instruction:
"Click "Retrieve" to automatically fill in data after typing a CHEMBL ID:"
to
"Enter ChemBl ID (CHEMBL####) and click "Retrieve" to automatically fill in data:"

**Comment by Luke-Malchow-Bergenthal** [comment]
Resolved in https://github.com/UPDDI/mps-database-server/commit/422ced1af0444265498433dfdf70952b15e69848
