### ISSUE TITLE
Link in Drug Trials should open in new tab

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#278]
The urls in the Drug Trial list display open in a new tab, but on the change page they open in the same tab.  The urls on the change page should open in a new tab.

**Comment by ahgough** [comment]
On further review, there is a button in the change page that says "Click here to open the URL in a new window", however, it opens the url in  a new tab instead.  Optimally, the url should directly open in a new tab, and the button should open it in a new window.

**Comment by Luke-Malchow-Bergenthal** [comment]
I might change the button to another url link and then just use the labels to specify which is for a new tab and for a new window.

**Comment by Luke-Malchow-Bergenthal** [comment]
Buttons added in https://github.com/UPDDI/mps-database-server/commit/9715038834db64d1b3f192aec689d7428c27237a
