### ISSUE TITLE
The Description and Condition fields in Drug Trials Admin are too small

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#281]
The Description field should be large enough to display a short description such as:
"Ciprofloxacin, a synthetic fluoroquinolone, has in vitro activity against a wide range of gram-negative
and gram-positive microorganisms. Its bactericidal action is achieved through
inhibition of topoisomerase II (DNA gyrase) and topoisomerase IV (both Type II
topoisomerases), which are required for bacterial DNA replication, transcription, repair, and
recombination." (This is under 400 ch, maybe display 500 ch max).
The Condition field does not need to be as large, but larger than it is.  Perhaps around 250 characters.

**Comment by Luke-Malchow-Bergenthal** [comment]
Resolved in https://github.com/UPDDI/mps-database-server/commit/c1cebfbf0df33660655f699e0835d4e80ce91bb4

**Comment by ahgough** [comment]
Sorry, but I was wrong about the size of the Condition field.  It should be the same size as the Description field.

**Comment by Luke-Malchow-Bergenthal** [comment]
That's no problem, I will change that.

**Comment by Luke-Malchow-Bergenthal** [comment]
Resolved in https://github.com/UPDDI/mps-database-server/commit/0634ecb41d77f5d86467e4f1b0a6e8b1980ab58a
