### ISSUE TITLE
Bioactivities table often times gives error, selection too large, then when reduced get no hits

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#288]
Try picking Target type = tissue, min count = 1, Target = Liver, All activities and all compounds gives error.  But hard to find any selection that will give any results.
Bioactivities with a = too many
b= 0
c, d, e = too many
f = 0
g = too many
h = 1
Not sure if this is a bug, but may be.

**Comment by Luke-Malchow-Bergenthal** [comment]
This was a result of some sloppy checks on my part. Currently the checks are if there are a large number of bioactivites or a large number of targets and greater than 15 compounds, then the parser stops.

**Comment by Luke-Malchow-Bergenthal** [comment]
Test on staging server currently returns only the top 5000 entries when generating a bioactivity table; displays a message indicating the total amount.

**Comment by Luke-Malchow-Bergenthal** [comment]
Limiting lists with a maximum number displayed is a fairly familiar idea. May add pagination or something of the sort later, but closing this issue for now.
