### ISSUE TITLE
Compound details in cluster interface do not scroll with the dendrogram

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#290]
Presently can only view 2-3 compounds at a time.  Scrolling would be helpful or if the structure was on the left and the details on the right, could probably see ~6 which would be better.  Alternatively, the structures could be displayed alone and the details as a tooltip.

**Comment by Luke-Malchow-Bergenthal** [comment]
I'll make it such that you can scroll through the compounds.

**Comment by Luke-Malchow-Bergenthal** [comment]
Scrollable compounds in cluster now live on the staging server.
