### ISSUE TITLE
We need to establish a user feedback mechanism.

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#291]
We should have an  integrated mechanism for users to post when they encounter a problem or if they don't understand something.  This could be as simple as a button that opens an email window to a predefined address, or something more sophisticated like UserVoice:
https://www.uservoice.com/tour/embedded/
If you go to the following website, you can see it in action.  Click on the feedback button in the lower right corner.
https://www.splitwise.com/login 
There are certainly other options out there, this is just the first one I came across.

**Comment by Luke-Malchow-Bergenthal** [comment]
Early feedback system powered by Django-Voice is now live on the staging server.

**Comment by Luke-Malchow-Bergenthal** [comment]
Though changes will need to be made to accommodate Django 1.7, the initial work is live on the production server.
