### ISSUE TITLE
When Drug Trial is locked the url links are not available

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#295]
The URL links to the source of the data should function whether or not the record is locked.  If this is only an issue in the Admin interface, the fix is not urgent.

**Comment by ahgough** [comment]
Let me correct that, the Source Link works, but the buttons to Open link in new Tab and Open link in new window do not work (are locked).

**Comment by Luke-Malchow-Bergenthal** [comment]
Open Link in New Tab and Open Link in New Window buttons will now work even when a drugtrial is locked: https://github.com/UPDDI/mps-database-server/commit/69d78c5024b643cdc7556a9c9ae2312574bc9bb5
