### ISSUE TITLE
User should be able to clone existing chip setups

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#302]
When I add a new setup I have the option to submit, or submit and add another.
But when I open an existing setup, I can only edit and submit.  If the user wants to clone an existing setup it would be useful to have the option to submit and add another when an existing setup is opened.

**Comment by Luke-Malchow-Bergenthal** [comment]
Now that you bring it up, I think it might be more straightforward to rename "Save and Add Another" to "Save and Clone."

**Comment by Luke-Malchow-Bergenthal** [comment]
This feature is live on the staging server.

**Comment by Luke-Malchow-Bergenthal** [comment]
This feature is now live on the production server: 7d09df4
