### ISSUE TITLE
User shoudl be warned when Control Chip contains a compound

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#303]
When submitting a test type 'Control' it would be useful to check the compound selection.  If the user is submitting a chip setup as control, with a selected compound, it would be nice to have a dialog pop up and say "Are you sure you want to include a Compound in your Control Chip?".  Yes would continue with submit and No would go back to the setup screen.

**Comment by Luke-Malchow-Bergenthal** [comment]
This feature is live on the staging server.

**Comment by Luke-Malchow-Bergenthal** [comment]
This feature is now live on the production server: https://github.com/UPDDI/mps-database-server/commit/7d09df4e78fd6817375ab472213c12e252f9dd92
